# Generated by Django 5.1.7 on 2025-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username_changed',
            field=models.BooleanField(default=False),
        ),
    ]
