# Generated by Django 5.1.7 on 2025-03-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
